// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameObservation = "observations"

// Observation mapped from table <observations>
type Observation struct {
	ID              string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	MetricID        string    `gorm:"column:metric_id;not null" json:"metric_id"`
	Value           float64   `gorm:"column:value;not null" json:"value"`
	Timestamp       time.Time `gorm:"column:timestamp;not null;default:now()" json:"timestamp"`
	IsReconstructed bool      `gorm:"column:is_reconstructed;not null" json:"is_reconstructed"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	Meta            string    `gorm:"column:meta" json:"meta"`
	UserID          string    `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName Observation's table name
func (*Observation) TableName() string {
	return TableNameObservation
}
