env: live
debug: true
# db: from-env
# systemUserID: from-env
metrics:
  - id: "0adb52bf-dcb1-4a19-83ed-e8d7778dd3fd"
    name: "Random from 1 to 10"
    schedule: "0 0 * * *"
    provider: "RandomProvider"
    options:
      max: 10.0
      min: 1.0